"""DAG visualisation — generates Mermaid diagrams from hurl-orchestra metadata.

Mermaid reference:
  Flowchart: https://mermaid.js.org/syntax/flowchart.html
"""

from __future__ import annotations

import logging
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from .orchestrator import GraphError, build_graph

_ESCAPE_MAP = str.maketrans(
    {
        "&": "&amp;",
        '"': "&quot;",
        "<": "&lt;",
        ">": "&gt;",
        "[": "&#91;",
        "]": "&#93;",
        "\n": " ",
        "\r": " ",
    }
)

logger = logging.getLogger(__name__)


def _safe_id_map(node_ids: Iterable[str]) -> dict[str, str]:
    """Map original node IDs to Mermaid-safe identifiers.

    Internal node IDs are opaque but guaranteed unique and Mermaid-safe.
    """
    result: dict[str, str] = {}
    for index, nid in enumerate(sorted(node_ids)):
        result[nid] = f"node_{index}"
    return result


def _node_label(node_id: str, node: dict[str, Any]) -> str:
    """Return the flowchart display label for a node.

    Format: ``id [out:N]`` or ``id [p:P, out:N]`` when priority is non-zero.
    """
    outputs = node.get("outputs")
    out = len(outputs) if isinstance(outputs, (list, tuple, set, dict)) else 0
    priority_raw = node.get("priority") or 0
    try:
        priority = int(priority_raw)
    except (TypeError, ValueError):
        logger.warning(
            "Node '%s' has invalid priority '%s'. Defaulting to 0.",
            node_id,
            priority_raw,
        )
        priority = 0

    safe_id = _escape_label(str(node_id))
    if priority != 0:
        return f"{safe_id} [p:{priority}, out:{out}]"
    return f"{safe_id} [out:{out}]"


def _escape_label(s: str) -> str:
    return s.translate(_ESCAPE_MAP)


def _render_flowchart(
    nodes: dict[str, dict[str, Any]],
    graph: dict[str, set[str]],
    safe_ids: dict[str, str],
    orientation: str = "LR",
) -> str:
    """Return a Mermaid flowchart block as a string."""
    lines = [f"flowchart {orientation}"]
    node_ids = sorted(nodes)
    for node_id in node_ids:
        label = _node_label(node_id, nodes[node_id])
        lines.append(f'    {safe_ids[node_id]}["{label}"]')
    for node_id in node_ids:
        for dep_id in sorted(graph.get(node_id, [])):
            dep_safe_id = safe_ids.get(dep_id)
            if dep_safe_id is None:
                raise GraphError(
                    "Dangling dependency detected while rendering: "
                    f"{dep_id} -> {node_id}"
                )
            lines.append(f"    {dep_safe_id} --> {safe_ids[node_id]}")
    return "\n".join(lines)


def build_diagram(hurl_paths: list[Path], orientation: str = "LR") -> str:
    """Build the full Markdown diagram string from *hurl_paths*.

    Raises ``GraphError`` if graph construction fails.
    """
    nodes, graph = build_graph(hurl_paths)

    safe_ids = _safe_id_map(nodes.keys())
    flowchart = _render_flowchart(nodes, graph, safe_ids, orientation)

    sections = [
        "# hurl-orchestra dependency diagram",
        f"## Flowchart\n\n```mermaid\n{flowchart}\n```",
        "_Generated by hurl-orchestra_",
    ]
    return "\n\n".join(sections) + "\n"


def write_diagram(
    hurl_paths: list[Path],
    output: str = "diagram.md",
    overwrite: bool = False,
) -> bool:
    """Generate the Mermaid diagram and write it to *output*.

    Pass ``'-'`` as *output* to write to stdout. Returns ``False`` on error.
    """
    try:
        content = build_diagram(hurl_paths)
    except (GraphError, OSError) as exc:
        logger.error("Diagram generation failed: %s", exc)
        return False

    if output == "-":
        try:
            print(content, end="")
        except BrokenPipeError:
            return False
        return True

    output_path = Path(output)
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        mode = "w" if overwrite else "x"
        with output_path.open(mode=mode, encoding="utf-8") as output_file:
            output_file.write(content)
    except FileExistsError:
        logger.error(
            "Diagram output already exists and overwrite is disabled: %s",
            output,
        )
        return False
    except IsADirectoryError:
        logger.error("Diagram output is a directory: %s", output)
        return False
    except OSError:
        logger.exception("Failed to write diagram to %s", output)
        return False
    return True
